title: Christopher Poole 
tagline: Science waits for no one.
owner: Christopher Poole
link: https://github.com/christopherpoole/
copyright: Copyright Christopher Poole 2012-2013


pygments: true
permalink: '/:title'
markdown: kramdown 

exclude: [README.md]

