title: Dr. Christopher Poole 
tagline: Science waits for no one.
owner: Dr. Christopher Poole
link: https://github.com/christopherpoole/
copyright: Copyright Christopher Poole 2012


pygments: true
permalink: '/:title'
markdown: kramdown 

exclude: [README.md]

